name: Insert Copyright to required files
on: [push]
jobs:
  lint:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      # Checking out the repository which is to be actioned
      - uses: actions/checkout@v2
      # Implementing action on repository
      - name: Runs action to insert copyright
        uses: VinnyBabuManjaly/insert-copyright-action@test_branch
      # Displaying output file contents
      - name: Display the path
        run: |
          ls -all
          cat test/test_file_b.txt
          cat test/test_file_a.txt
        shell: bash

