name: Insert Copyright to required files
on: [push]
jobs:
  build:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      # Checking out the repository which is to be actioned
      - uses: actions/checkout@v2
      # Implementing action on repository
      - name: Runs action to insert copyright
        uses: VinnyBabuManjaly/insert-copyright-action@test_branch
        with:
          CopyrightString: 'copyright check\ncopyright check\n'
          FilePath: 'tests'
          FileType: '.py,.txt'
       
