name: Insert Copyright to required files
on: [push]
jobs:
  build:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      # Checking out the repository which is to be actioned
      - uses: actions/checkout@v2
      # Implementing action on repository
      - name: Runs action to insert copyright
        uses: VinnyBabuManjaly/insert-copyright-action@test_branch
        with:
          CopyrightString: 'copyright check\n'
          FilePath: 'test'
          FileType: '[".py", ".txt"]'
      # Displaying output file contents
      - name: Display the path
        run: |
          ls -all
          cat test/test_file_b.txt
          cat test/test_file_a.txt
        shell: bash
      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add test/
          git commit -m "Add changes"
          git checkout -b test_branch_a
          git push origin test_branch_a

